services:
  # Oracle Database Lite
  db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-db-clase7
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=password123
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      - ENABLE_FORCE_LOGGING=true
      - TZ=America/Guatemala
    volumes:
      - ./oracle-db:/opt/oracle/oradata
  
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    volumes:
      - ./backend-node/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - USER_DB="C##fernando"
      - PASSWORD_DB="password123"
      - CONNECT_STRING="oracle-db-clase7:1521/FREE"
    command: npm run start:dev
  
volumes:
  oracle-db:
    external: true
  