services:
  # Oracle Database Lite
  db-lite:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-db-lite
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=Welcome1
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      - ENABLE_FORCE_LOGGING=true
    volumes:
      - ./oracledb-lite:/opt/oracle/oradata
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db-lite
    environment:
      - PORT=3000
    command: npm run start:dev
    
  
volumes:
  oracledb-lite:
    external: true
  